spring:
  application:
    name: document-management-service
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        default_batch_fetch_size: 50
        order_inserts: true
        order_updates: true
        order_deletes: true
        generate_statistics: true
  data:
    rest:
      base-path: /api/v1
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

app:
  name: document-management-service

logging:
  level:
    root: info
