spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:${DB_BASE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

environment: dev