spring:
  application:
    name: document-management-service
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

app:
  name: document-management-service