input {
  tcp {
    port => 50000
    codec => json_lines {
        ecs_compatibility => "disabled"
    }
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
  }
}